// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	test "github.com/pz2147/p-gateway-1/internal/handler/test"
	"github.com/pz2147/p-gateway-1/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/test",
				Handler: test.TestApiHandler(serverCtx),
			},
		},
	)
}
